
package de.is2.mtext.soap.demo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BayerischeD3OMAdapterWSService", targetNamespace = "http://omAdapter.bayerische.kwsoft.de/", wsdlLocation = "http://iswasdev2.bbv.de:9086/OMAdapter/BayerischeD3OMAdapterWSService/BayerischeD3OMAdapterWSService.wsdl")
public class BayerischeD3OMAdapterWSService
    extends Service
{

    private final static URL BAYERISCHED3OMADAPTERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BAYERISCHED3OMADAPTERWSSERVICE_EXCEPTION;
    private final static QName BAYERISCHED3OMADAPTERWSSERVICE_QNAME = new QName("http://omAdapter.bayerische.kwsoft.de/", "BayerischeD3OMAdapterWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://iswasdev2.bbv.de:9086/OMAdapter/BayerischeD3OMAdapterWSService/BayerischeD3OMAdapterWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BAYERISCHED3OMADAPTERWSSERVICE_WSDL_LOCATION = url;
        BAYERISCHED3OMADAPTERWSSERVICE_EXCEPTION = e;
    }

    public BayerischeD3OMAdapterWSService() {
        super(__getWsdlLocation(), BAYERISCHED3OMADAPTERWSSERVICE_QNAME);
    }

    public BayerischeD3OMAdapterWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BAYERISCHED3OMADAPTERWSSERVICE_QNAME, features);
    }

    public BayerischeD3OMAdapterWSService(URL wsdlLocation) {
        super(wsdlLocation, BAYERISCHED3OMADAPTERWSSERVICE_QNAME);
    }

    public BayerischeD3OMAdapterWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BAYERISCHED3OMADAPTERWSSERVICE_QNAME, features);
    }

    public BayerischeD3OMAdapterWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BayerischeD3OMAdapterWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BayerischeD3OMAdapterWS
     */
    @WebEndpoint(name = "BayerischeD3OMAdapterWSPort")
    public BayerischeD3OMAdapterWS getBayerischeD3OMAdapterWSPort() {
        return super.getPort(new QName("http://omAdapter.bayerische.kwsoft.de/", "BayerischeD3OMAdapterWSPort"), BayerischeD3OMAdapterWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BayerischeD3OMAdapterWS
     */
    @WebEndpoint(name = "BayerischeD3OMAdapterWSPort")
    public BayerischeD3OMAdapterWS getBayerischeD3OMAdapterWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://omAdapter.bayerische.kwsoft.de/", "BayerischeD3OMAdapterWSPort"), BayerischeD3OMAdapterWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BAYERISCHED3OMADAPTERWSSERVICE_EXCEPTION!= null) {
            throw BAYERISCHED3OMADAPTERWSSERVICE_EXCEPTION;
        }
        return BAYERISCHED3OMADAPTERWSSERVICE_WSDL_LOCATION;
    }

}
